name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  equatable: ^2.0.3
  rxdart: ^0.28.0

  authentication_client:
    path: ../authentication_client/authentication_client
  deep_link_client:
    path: ../deep_link_client/deep_link_client
  package_info_client:
    path: ../package_info_client
  storage:
    path: ../storage/storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
