name: zimble
description: RFID app
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:

  #custom packages
  analytics_repository:
    path: packages/analytics_repository
  app_ui:
    path: packages/app_ui
  authentication_client:
    path: packages/authentication_client/authentication_client
  deep_link_client:
    path: packages/deep_link_client/deep_link_client
  drift_storage:
    path: packages/storage/drift_storage
  email_launcher:
    path: packages/email_launcher
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_deep_link_client:
    path: packages/deep_link_client/firebase_deep_link_client
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client
  form_inputs:
    path: packages/form_inputs
  notifications_repository:
    path: packages/notifications_repository
  permission_client:
    path: packages/permission_client
  persistent_storage:
    path: packages/storage/persistent_storage
  reader_client:
    path: packages/reader_client/reader_client
  reader_repository:
    path: packages/reader_repository
  token_storage:
    path: packages/authentication_client/token_storage
  user_repository:
    path: packages/user_repository

  ## flutter package imports

  #dynamic text resizing
  auto_size_text: ^3.0.0

  #bloc core
  bloc: ^8.1.4

  #bloc_concurrency for stream transformers
  bloc_concurrency: ^0.2.0

  #network Requests
  dio: ^5.4.0

  #SQL local storage
  drift: ^2.22.0

  #Class and object hash/id matching
  equatable: ^2.0.5

  #firebase core and tools
  firebase_analytics: ^11.3.1
  firebase_auth_platform_interface: ^7.4.5
  firebase_core: ^3.4.1
  firebase_crashlytics: ^4.1.1
  firebase_dynamic_links: ^6.0.6
  firebase_messaging: ^15.1.1

  #flow_builder for route generation
  flow_builder: ^0.0.7

  #flutter SDK
  flutter:
    sdk: flutter

  #flutter implementation of Bloc pattern
  flutter_bloc: ^8.1.6

  #Native International translations based on location
  flutter_localizations:
    sdk: flutter

  #SVG icon support
  flutter_svg: ^2.0.5

  #Font_awesome support
  font_awesome_flutter: ^10.1.0

  #GoRouter for navigation routes
  go_router: ^14.6.1
  url_strategy:

  #HydratedBloc for persistent local state management across app start/close
  hydrated_bloc: ^9.0.0

  #dateFormat
  intl: ^0.19.0

  #json serialization for data channels to device
  json_annotation: ^4.9.0

  #NFC implementation
  nfc_manager: ^3.5.0

  #Bluetooth Permissions for flutter
  permission_handler: ^11.1.0

  #Platform Independent helpers
  platform: ^3.0.2

  #path_provider:
  path_provider: ^2.1.4

  #Network Requests
  retrofit: ^4.1.0

  #Updated Stream Manager
  rxdart: ^0.28.0

  #SQL Libraries
  sqlite3_flutter_libs: ^0.5.0

  #Access to device shared preferences
  shared_preferences: ^2.0.15

  #Extrenal URL launcher
  url_launcher: ^6.3.1


dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/images/reader_images/
    - assets/images/logos/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/mtg_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
