name: reader_repository
description: Reader Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  rxdart: ^0.28.0

  #custom packages
  reader_client:
    path: ../reader_client/reader_client
  storage:
    path: ../storage/storage
  drift_storage:
    path: ../storage/drift_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
