name: drift_storage
description: Drift Storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.22.1
  drift_flutter: ^0.2.2
  sqlite3_flutter_libs: ^0.5.27
  path_provider: ^2.1.5
  path: 1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.13
